blank_issues_enabled: true
contact_links:
  - name: App Submission
    url: https://forms.gle/redZCVMwkuhvuDtb9
    about: Submit new app to catalog
  - name: Email
    url: https://webcatalog.app/help
    about: Contact the developer directly