name: Cask

on:
  push:
    branches:
      - master # trigger CI whenever a new commit is pushed to master branch
  pull_request:
    branches:
      - master
      - next
    paths:
      - '.github/workflows/cask.yml'

jobs:
  publish:
    runs-on: macos-latest # run CI with latest available macOS version

    steps:
    - uses: actions/checkout@v2 # clone the reposity
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Get version
      id: get_version
      run: echo ::set-output name=version::$(node -p -e "require('./package.json').version")
    - name: Update Cask
      # GitHub Actions set HOMEBREW_NO_AUTO_UPDATE=1 by default
      # So `brew update` needs to be run manually
      run: |
        brew update
        brew tap vitorgalvao/tiny-scripts
        brew install cask-repair
        git config --global user.email "quang.lam@webcatalog.app"
        git config --global user.name "Quang Lam (GitHub Actions)"
        (cd $(brew --repository) && hub issue)
        HOMEBREW_NO_COLOR=1 cask-repair --cask-version $(node -p -e "require('./package.json').version") --blind-submit webcatalog
      # only runs if version is not a prerelease (not ending with -beta, -alpha, rc)
      if: contains(steps.get_version.outputs.version, '-'') != 'true'
      env:
        GITHUB_USER: quanglam2807
        GITHUB_TOKEN: ${{ secrets.MASTER_GITHUB_TOKEN }}